create table account (
       id bigint generated by default as identity,
        additionalInfo varchar(255),
        birthDay date,
        email varchar(255) not null,
        firstName varchar(255) not null,
        icq varchar(255),
        lastName varchar(255),
        password varchar(255) not null,
        photo blob,
        regDate date,
        role varchar(255),
        skype varchar(255),
        primary key (id)
    );

    create table community (
       id bigint generated by default as identity,
        createDate date,
        creatorId bigint not null,
        description varchar(255),
        name varchar(255) not null,
        picture blob,
        primary key (id)
    );

    create table community_message (
       id bigint generated by default as identity,
        authorId bigint,
        createDate timestamp not null,
        text varchar(2500) not null,
        community_id bigint,
        primary key (id)
    );

    create table community_request (
       id bigint generated by default as identity,
        accepted boolean,
        role varchar(255),
        community_id bigint,
        from_id bigint,
        primary key (id)
    );

    create table friend_request (
       id bigint generated by default as identity,
        accepted boolean,
        from_id bigint,
        to_id bigint,
        primary key (id)
    );

    create table personal_message (
       id bigint generated by default as identity,
        createDate timestamp not null,
        text varchar(2500) not null,
        from_id bigint,
        to_id bigint,
        primary key (id)
    );

    create table phone (
       id bigint generated by default as identity,
        number varchar(255) not null,
        type varchar(255) not null,
        phoneOwner_id bigint,
        primary key (id)
    );

    create table wall_message (
       id bigint generated by default as identity,
        createDate timestamp not null,
        text varchar(2500) not null,
        account_id bigint,
        primary key (id)
    );

    alter table community_message
       add constraint FKs64vqpr0lymc33b6qpvp7a3jh
       foreign key (community_id)
       references community;

    alter table community_request
       add constraint FK33uuraje5eu7ubhmoyg5pabqj
       foreign key (community_id)
       references community;

    alter table community_request
       add constraint FKsom2rtdxw2est74afm1vp2958
       foreign key (from_id)
       references account;

    alter table friend_request
       add constraint FKk3wp8oifqq8w8l9fhgll4ae2v
       foreign key (from_id)
       references account;

    alter table friend_request
       add constraint FKi4gif743dwaptehs8lluwpaj8
       foreign key (to_id)
       references account;

    alter table personal_message
       add constraint FKdrobwgcd0mp183hpmyhuk258r
       foreign key (from_id)
       references account;

    alter table personal_message
       add constraint FK8my22w9lsmhwas3p5b8gdq1ql
       foreign key (to_id)
       references account;

    alter table phone
       add constraint FKbr8y67b8i2ailbwfqxvrm0dv8
       foreign key (phoneOwner_id)
       references account;

    alter table wall_message
       add constraint FK37va8egou4aprfq974147sosj
       foreign key (account_id)
       references account;